/*----------------------------------------------------------------------------------*/
/* Product:            Visual Data Mining and Machine Learning                      */
/* Release Version:    V2022.09                                                     */
/* Component Version:  V2022.09                                                     */
/* CAS Version:        V.04.00M0P09192022                                           */
/* SAS Version:        V.04.00M0P091922                                             */
/* Site Number:        70180938                                                     */
/* Host:               sas-cas-server-default-client                                */
/* Encoding:           utf-8                                                        */
/* Java Encoding:      UTF8                                                         */
/* Locale:             en_US                                                        */
/* Project GUID:       ea1d8e57-b1a9-4964-84c2-e088999385ea                         */
/* Node GUID:          ec4dc9de-322c-43b7-aa5f-63385e248967                         */
/* Node Id:            DZMQ9L6RHK6P98COBXCJVDV1J                                    */
/* Algorithm:          Linear Regression                                            */
/* Generated by:       geldmui@gelenable.sas.com                                    */
/* Date:               17NOV2022:04:28:19                                           */
/*----------------------------------------------------------------------------------*/
*------------------------------------------------------------*;
*Nodeid: _90EVTVNRW5R9H8YSD55ZKYN8U;
*------------------------------------------------------------*;
*------------------------------------------------------------*;
*Nodeid: _CPGQMKXO935KIZHJ43K4242MM;
*------------------------------------------------------------*;
*------------------------------------------------------------*;
*Nodeid: _DZMQ9L6RHK6P98COBXCJVDV1J;
*------------------------------------------------------------*;
   /*---------------------------------------------------------
     Generated SAS Scoring Code
     Date: 17Nov2022:04:28:18
     -------------------------------------------------------*/

   drop _badval_ _linp_ _temp_ _i_ _j_;
   _badval_ = 0;
   _linp_   = 0;
   _temp_   = 0;
   _i_      = 0;
   _j_      = 0;

   array _xrow_77138452_0_{14} _temporary_;
   array _beta_77138452_0_{14} _temporary_ (    11999.9999999999
                      23000
                      68000
                      16000
                      28000
          -6999.99999999998
          -3999.99999999998
                          0
                          0
        1.6608936448392E-11
          -3999.99999999998
                          0
                          0
                          0);

   length _Miles_ $6; drop _Miles_;
   _Miles_ = left(trim(put(Miles,BEST6.)));
   do _i_=1 to 14; _xrow_77138452_0_{_i_} = 0; end;

   _xrow_77138452_0_[1] = 1;

   _temp_ = 1;
   select (_Miles_);
      when ('4000') _xrow_77138452_0_[2] = _temp_;
      when ('5000') _xrow_77138452_0_[3] = _temp_;
      when ('20000') _xrow_77138452_0_[4] = _temp_;
      when ('40000') _xrow_77138452_0_[5] = _temp_;
      when ('50000') _xrow_77138452_0_[6] = _temp_;
      when ('59000') _xrow_77138452_0_[7] = _temp_;
      when ('68000') _xrow_77138452_0_[8] = _temp_;
      when ('70000') _xrow_77138452_0_[9] = _temp_;
      when ('80000') _xrow_77138452_0_[10] = _temp_;
      when ('82000') _xrow_77138452_0_[11] = _temp_;
      when ('90000') _xrow_77138452_0_[12] = _temp_;
      when ('100000') _xrow_77138452_0_[13] = _temp_;
      when ('270000') _xrow_77138452_0_[14] = _temp_;
      otherwise do; _badval_ = 1; goto skip_77138452_0; end;
   end;

   do _i_=1 to 14;
      _linp_ + _xrow_77138452_0_{_i_} * _beta_77138452_0_{_i_};
   end;

   skip_77138452_0:
   label P_BlueBookPrice = 'Predicted: BlueBookPrice';
   if (_badval_ eq 0) and not missing(_linp_) then do;
      P_BlueBookPrice = _linp_;
   end; else do;
      _linp_ = .;
      P_BlueBookPrice = .;
   end;


   *------------------------------------------------------------*;
   * Accounting for missing predicted variable;
   *------------------------------------------------------------*;
   label "P_BlueBookPrice"n ='Predicted: BlueBookPrice';
   if "P_BlueBookPrice"n = . then "P_BlueBookPrice"n =22142.857143;
*------------------------------------------------------------*;
* Generating fixed output names;
*------------------------------------------------------------*;
Length EM_PREDICTION 8;
LABEL EM_PREDICTION= "Prediction for BlueBookPrice";
EM_PREDICTION= 'P_BlueBookPrice'n;
